// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Candidato struct {
	ID         string `json:"id"`
	Nombre     string `json:"nombre"`
	Documento  string `json:"documento"`
	Partido    string `json:"partido"`
	FotoURL    string `json:"fotoUrl"`
	EleccionID string `json:"eleccionId"`
	CreatedAt  string `json:"createdAt"`
	UpdatedAt  string `json:"updatedAt"`
}

type Eleccion struct {
	ID           string       `json:"id"`
	Nombre       string       `json:"nombre"`
	TipoEleccion TipoEleccion `json:"tipoEleccion"`
	FechaInicio  int          `json:"fechaInicio"`
	FechaFin     int          `json:"fechaFin"`
	Candidatos   []*Candidato `json:"candidatos"`
	Puntos       []*Punto     `json:"puntos"`
	Nodos        []*Nodo      `json:"nodos"`
	CreatedAt    string       `json:"createdAt"`
	UpdatedAt    string       `json:"updatedAt"`
}

type Jurado struct {
	ID        string `json:"id"`
	Nombre    string `json:"nombre"`
	Documento string `json:"documento"`
	Usuario   string `json:"usuario"`
	PuntoID   string `json:"puntoId"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type Nodo struct {
	ID         string `json:"id"`
	Activo     bool   `json:"activo"`
	EleccionID string `json:"eleccionId"`
	CreatedAt  string `json:"createdAt"`
	UpdatedAt  string `json:"updatedAt"`
}

type Punto struct {
	ID         string      `json:"id"`
	Nombre     string      `json:"nombre"`
	Latitud    float64     `json:"latitud"`
	Longitud   float64     `json:"longitud"`
	Activo     bool        `json:"activo"`
	EleccionID string      `json:"eleccionId"`
	Jurados    []*Jurado   `json:"jurados"`
	Terminales []*Terminal `json:"terminales"`
	CreatedAt  string      `json:"createdAt"`
	UpdatedAt  string      `json:"updatedAt"`
}

type Query struct {
}

type Terminal struct {
	ID           string     `json:"id"`
	Activo       bool       `json:"activo"`
	PuntoID      string     `json:"puntoId"`
	ClavePublica string     `json:"clavePublica"`
	Votantes     []*Votante `json:"votantes"`
	CreatedAt    string     `json:"createdAt"`
	UpdatedAt    string     `json:"updatedAt"`
}

type Votante struct {
	ID         string `json:"id"`
	Nombre     string `json:"nombre"`
	Documento  string `json:"documento"`
	TerminalID string `json:"terminalId"`
	CreatedAt  string `json:"createdAt"`
	UpdatedAt  string `json:"updatedAt"`
}

type TipoEleccion string

const (
	TipoEleccionPresidencial TipoEleccion = "PRESIDENCIAL"
	TipoEleccionLegislativa  TipoEleccion = "LEGISLATIVA"
	TipoEleccionTerritorial  TipoEleccion = "TERRITORIAL"
)

var AllTipoEleccion = []TipoEleccion{
	TipoEleccionPresidencial,
	TipoEleccionLegislativa,
	TipoEleccionTerritorial,
}

func (e TipoEleccion) IsValid() bool {
	switch e {
	case TipoEleccionPresidencial, TipoEleccionLegislativa, TipoEleccionTerritorial:
		return true
	}
	return false
}

func (e TipoEleccion) String() string {
	return string(e)
}

func (e *TipoEleccion) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TipoEleccion(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TipoEleccion", str)
	}
	return nil
}

func (e TipoEleccion) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TipoEleccion) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TipoEleccion) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
